apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  namespace: {{.Values.namespace.name}}
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{.Values.maxSurge}}
      maxUnavailable: {{.Values.maxUnavailable}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      {{- if .Values.dockercfg}}
      imagePullSecrets:
      - name: {{.Values.name}}-dockercfg
      {{- end}}

      {{- if .Values.agentSidecar.enabled }}
      initContainers:
        - name: et-agent-sidecar
          image: {{.Values.agentSidecar.image}}
          imagePullPolicy: {{ .Values.agentSidecar.pullPolicy }}
          volumeMounts:
          - name: et-agent
            mountPath: /opt/harness-et-agent
      {{- end }}

      containers:
      - name: {{.Values.name}}
        {{- if or .Values.env.config .Values.env.secrets}}
        envFrom:
        {{- if .Values.env.config}}
        - configMapRef:
            name: {{.Values.name}}
        {{- end}}
        {{- if .Values.env.secrets}}
        - secretRef:
            name: {{.Values.name}}
        {{- end}}
        {{- end}}

        {{- if .Values.agentSidecar.enabled}}
        env:
          - name: JAVA_TOOL_OPTIONS
            value: "-agentpath:/opt/harness-et-agent/harness/lib/libETAgent.so=debug.logconsole"
        {{- end}}

        image: {{.Values.image}}
        imagePullPolicy: {{.Values.imagePullPolicy}}

        resources:
          limits:
            memory: {{.Values.memLimit | quote}}
            cpu: {{.Values.cpuLimit | quote}}
          requests:
            memory: {{.Values.memRequest | quote}}
            cpu: {{.Values.cpuRequest | quote}}

        {{- if .Values.agentSidecar.enabled }}
        volumeMounts:
          - name: et-agent
            mountPath: /opt/harness-et-agent
        {{- end }}

      {{- if .Values.agentSidecar.enabled }}
      volumes:
        - name: et-agent
          emptyDir: {}
      {{- end }}
